[package]
name = "sch_driver"
version = "0.0.0"
authors = ["Fredrik Stave <fredrik.stave@schibsted.com>"]
edition = "2018"

#
# [lib]
# crate-type = ["dylib"]
#

[dependencies]
libc = "0.2"
tracing = "0.1"
sch_ast = { path = "../sch_ast" }
